<?php 

	@define('dashboard_1', utf8_encode('Nombre empresa'));
	@define('dashboard_2', utf8_encode('Inicio'));
	@define('dashboard_3', utf8_encode('Buscar'));
	@define('dashboard_4', utf8_encode('Ingresa el nombre de tu producto '));
	@define('dashboard_5', utf8_encode('Anterior '));
	@define('dashboard_6', utf8_encode('Siguiente '));
	@define('dashboard_7', utf8_encode('Inicia sesion '));
	@define('dashboard_8', utf8_encode('Usuario'));
	@define('dashboard_9', utf8_encode('Clave'));
	@define('dashboard_10', utf8_encode('Guardar'));
	@define('dashboard_11', utf8_encode('Iniciar sesion'));
	@define('dashboard_12', utf8_encode('Ingresar'));
	@define('dashboard_13', utf8_encode('Usuario o clave invalidos'));
	@define('dashboard_14', utf8_encode('Error'));
	@define('dashboard_15', utf8_encode('Exito'));
	@define('dashboard_16', utf8_encode('Sesion iniciada'));
	@define('dashboard_17', utf8_encode('Crear productos'));
	@define('dashboard_18', utf8_encode('Nombre'));
	@define('dashboard_19', utf8_encode('Cantidad '));
	@define('dashboard_20', utf8_encode('Precio '));
	@define('dashboard_21', utf8_encode('Descripcion '));
	@define('dashboard_22', utf8_encode('Palabra clave '));
	@define('dashboard_23', utf8_encode('Categoria '));
	@define('dashboard_24', utf8_encode('visible '));
	@define('dashboard_25', utf8_encode('Stock '));
	@define('dashboard_26', utf8_encode('Guardar '));
	@define('dashboard_27', utf8_encode('Opciones '));
	@define('dashboard_28', utf8_encode('Lista de productos '));
	@define('dashboard_29', utf8_encode('Foto '));
	@define('dashboard_30', utf8_encode('Editar '));
	@define('dashboard_31', utf8_encode('Eliminar '));
	@define('dashboard_32', utf8_encode('Producto registrado '));
	@define('dashboard_33', utf8_encode('Error Producto registrado '));
	@define('dashboard_34', utf8_encode('Visible '));
	@define('dashboard_35', utf8_encode('No visible '));
	@define('dashboard_36', utf8_encode('Stock '));
	@define('dashboard_37', utf8_encode('Sin Stock '));
	@define('dashboard_38', utf8_encode('Producto eliminado '));
	@define('dashboard_39', utf8_encode('Producto no eliminado '));
	@define('dashboard_40', utf8_encode('Nombre de la pagina '));
	@define('dashboard_41', utf8_encode('Inicio	 '));
	@define('dashboard_42', utf8_encode('Productos'));
	@define('dashboard_43', utf8_encode('Lista productos')); 
	@define('dashboard_44', utf8_encode('Atras')); 
	@define('dashboard_45', utf8_encode('Otro')); 
	@define('dashboard_46', utf8_encode('Editar producto')); 
	@define('dashboard_47', utf8_encode('Link mercado libre'));
	@define('dashboard_48', utf8_encode('Modificacion exitosa'));
	@define('dashboard_49', utf8_encode('no se pudo modificar '));
	@define('dashboard_50', utf8_encode('Subir imagenes '));
	@define('dashboard_51', utf8_encode('Seleccionar imagen '));
	@define('dashboard_52', utf8_encode('Subir imagen   '));
	@define('dashboard_53', utf8_encode('Imagen subida'));
	@define('dashboard_54', utf8_encode('Error al subir imagen'));
	@define('dashboard_55', utf8_encode('Advertencia'));
	@define('dashboard_56', utf8_encode('No se ha seleccionado ninguna imagen'));
	@define('dashboard_57', utf8_encode('El nombre de la imagen esta repetido'));
	@define('dashboard_58', utf8_encode('Imagenes subidas'));
	@define('dashboard_59', utf8_encode('Este producto no tiene imagenes relacionadas'));
	@define('dashboard_60', utf8_encode('Imagenes relacionadas'));
	@define('dashboard_61', utf8_encode('Anterior'));
	@define('dashboard_62', utf8_encode('Siguiete'));
	@define('dashboard_63', utf8_encode('Tiene foto'));
	@define('dashboard_64', utf8_encode('Sin foto'));
	@define('dashboard_65', utf8_encode('Categorias'));
	@define('dashboard_66', utf8_encode('Nombre'));
	@define('dashboard_67', utf8_encode('Descripcion'));
	@define('dashboard_68', utf8_encode('Categoria padre'));
	@define('dashboard_69', utf8_encode('Opciones'));
	@define('dashboard_70', utf8_encode('Lista categoria'));
	@define('dashboard_71', utf8_encode('Sin categoria padre'));
	@define('dashboard_72', utf8_encode('Registrar categoria'));
	@define('dashboard_73', utf8_encode('Registrar'));
	@define('dashboard_74', utf8_encode(' Categoria registrada'));
	@define('dashboard_75', utf8_encode(' Categoria no registrada'));
	@define('dashboard_76', utf8_encode(' Categoria eliminada'));
	@define('dashboard_77', utf8_encode(' Categoria no eliminada'));
	@define('dashboard_78', utf8_encode('Editar categoria'));
	@define('dashboard_79', utf8_encode('Guardar'));
	@define('dashboard_80', utf8_encode('Cancelar'));
	@define('dashboard_81', utf8_encode('¡Hola! Para continuar, ingresa
tu usuario o e-mail '));
 ?>